In [9]:
from urllib.request import urlopen
from bs4 import BeautifulSoup as soup

url_template = "http://books.toscrape.com/catalogue/page-{}.html"
img_url_template = "http://books.toscrape.com"
img_urls = []
book_titles = []

with open('file.csv', 'w', encoding='utf-8') as f:
    heading = 'image_url' + ',' + 'book_title' + ',' + 'product_price' + '\n'
    f.write(heading)
    
    for i in range(1, 6):
        url = url_template.format(i)
        data = urlopen(url)
        page_html = data.read()
        page_parsed_html = soup(page_html, 'html.parser')
        books = page_parsed_html.findAll('article', {'class': 'product_pod'})

        for j in range(0, len(books)):
            book_url = books[j].img.attrs['src']
            book_title = books[j].findAll('a')[1].attrs['title']
            book_price = books[j].findAll('p')[1].text
            bookimage_url = img_url_template + book_url[2:]
            img_urls.append(bookimage_url)
            book_titles.append(book_title)
            
            if '"' in book_title:
                book_title=book_title.replace('"','')
            
            if ',' in book_url:
                book_url = '"'+book_url+'"'
            
            if ',' in book_title:
                book_title = '"'+book_title+'"'
            
            if ',' in book_price:
                book_price = '"'+book_price+'"'
            
            
            s=book_url+','+book_title+','+book_price+'\n'
            f.write(s)

data.close()

## To display all the rows of a data frame

pandas.set_option('display.max_rows', None)

In [10]:
import pandas as pd

df = pd.read_csv('file.csv')
df.head(n=1000)

,image_url,book_title,product_price
0,../media/cache/2c/da/2cdad67c44b002e7ead0cc356...,A Light in the Attic,£51.77
1,../media/cache/26/0c/260c6ae16bce31c8f8c95dadd...,Tipping the Velvet,£53.74
2,../media/cache/3e/ef/3eef99c9d9adef34639f51066...,Soumission,£50.10
3,../media/cache/32/51/3251cf3a3412f53f339e42cac...,Sharp Objects,£47.82
4,../media/cache/be/a5/bea5697f2534a2f86a3ef27b5...,Sapiens: A Brief History of Humankind,£54.23
...,...,...,...
95,../media/cache/5f/b1/5fb1bf88dcfda795606745ce3...,Lumberjanes Vol. 3: A Terrible Plan (Lumberjan...,£19.92
96,../media/cache/98/d1/98d1c979c4bac9e147a671894...,"Layered: Baking, Building, and Styling Spectac...",£40.11
97,../media/cache/5f/52/5f52b1bc6d45daab2e330c744...,Judo: Seven Steps to Black Belt (an Introducto...,£53.90
98,../media/cache/93/63/9363f0065fbad5689f44fcf6e...,Join,£35.67
99,../media/cache/fe/ea/feeafd2ad7b3077f8e74cbb1d...,In the Country We Love: My Family Divided,£22.00

In [15]:
#  Scraping images of book
import requests

for i in range(0,len(img_urls)):
    r = requests.get(img_urls[i])
    
    file_name = 'images/untitled'+str(i)+'.jpg'
    with open(file_name,'wb') as f:
        f.write(r.content)