In [1]:
from urllib.request import urlopen
from bs4 import BeautifulSoup as soup

url_template = "http://books.toscrape.com/catalogue/page-{}.html"

with open('file.csv', 'w', encoding='utf-8') as f:
    heading = 'image_url' + ',' + 'book_title' + ',' + 'product_price' + '\n'
    f.write(heading)
    for i in range(1, 51):
        url = url_template.format(i)
        data = urlopen(url)
        page_html = data.read()
        page_parsed_html = soup(page_html, 'html.parser')
        books = page_parsed_html.findAll('article', {'class': 'product_pod'})

        for j in range(0, len(books)):
            book_url = books[j].img.attrs['src']
            book_title = books[j].findAll('a')[1].attrs['title']
            book_price = books[j].findAll('p')[1].text
            
            if '"' in book_title:
                book_title=book_title.replace('"','')
            
            if ',' in book_url:
                book_url = '"'+book_url+'"'
            
            if ',' in book_title:
                book_title = '"'+book_title+'"'
            
            if ',' in book_price:
                book_price = '"'+book_price+'"'
            
            
            s=book_url+','+book_title+','+book_price+'\n'
            f.write(s)

data.close()

## To display all the rows of a data frame

pd.set_option('display.max_rows', None)

In [2]:
import pandas as pd

df = pd.read_csv('file.csv')
df.head(n=1000)

,image_url,book_title,product_price
0,../media/cache/2c/da/2cdad67c44b002e7ead0cc356...,A Light in the Attic,£51.77
1,../media/cache/26/0c/260c6ae16bce31c8f8c95dadd...,Tipping the Velvet,£53.74
2,../media/cache/3e/ef/3eef99c9d9adef34639f51066...,Soumission,£50.10
3,../media/cache/32/51/3251cf3a3412f53f339e42cac...,Sharp Objects,£47.82
4,../media/cache/be/a5/bea5697f2534a2f86a3ef27b5...,Sapiens: A Brief History of Humankind,£54.23
...,...,...,...
995,../media/cache/96/ee/96ee77d71a31b7694dac6855f...,Alice in Wonderland (Alice's Adventures in Won...,£55.53
996,../media/cache/09/7c/097cb5ecc6fb3fbe1690cf0cb...,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",£57.06
997,../media/cache/1b/5f/1b5ff86f3c75e51e24c573d3f...,A Spy's Devotion (The Regency Spies of London #1),£16.97
998,../media/cache/2b/41/2b4161c5b72a4ae386b644682...,1st to Die (Women's Murder Club #1),£53.98
999,../media/cache/d7/0f/d70f7edd92705c45a82118c3f...,"1,000 Places to See Before You Die",£26.08